### ISSUE TITLE
Project not compiling | R8 error with Vungle mediation adaptor 

### ISSUE THREAD

**Issue by mmanuja** [newrelic/newrelic-android-agent#316]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

I am getting this error when I have added vungle applovin mediation adaptor. 
Getting this error: com.android.tools.r8.internal.Ge: Different stack heights at jump target: 2 != 1

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Steps to Reproduce

Add new relic in your app. Add applovin and vungle mediation adapter

[NOTE]: # ( Please be as specific as possible. )

## Expected Behavior

It should work. If I am removing vungle it is working fine. 

[NOTE]: # ( Tell us what you expected to happen. )

## Relevant Logs / Console output

com.android.tools.r8.internal.Ge: Different stack heights at jump target: 2 != 1
Caused by: org.gradle.tooling.BuildException: Failed to process: /Users/mohitmanuja/Documents/impel/Dippy-android/app/build/intermediates/classes/debug/ALL/newrelicTransformClassesForDebug/classes.jar
Caused by: com.android.builder.dexing.DexArchiveBuilderException: Failed to process: /Users/mohitmanuja/Documents/impel/Dippy-android/app/build/intermediates/classes/debug/ALL/newrelicTransformClassesForDebug/classes.jar
Caused by: com.android.builder.dexing.DexArchiveBuilderException: Error while dexing.
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, position: Lcom/vungle/ads/internal/load/BaseAdLoader;injectMraidJS(Ljava/io/File;)Z, origin: /Users/mohitmanuja/Documents/impel/Dippy-android/app/build/intermediates/classes/debug/ALL/newrelicTransformClassesForDebug/classes.jar:com/vungle/ads/internal/load/BaseAdLoader.class
	Caused by: java.util.concurrent.ExecutionException: com.android.tools.r8.internal.so: com.android.tools.r8.internal.Ge: Different stack heights at jump target: 2 != 1
	Caused by: com.android.tools.r8.internal.so: com.android.tools.r8.internal.Ge: Different stack heights at jump target: 2 != 1
	Caused by: [CIRCULAR REFERENCE: com.android.tools.r8.internal.Ge: Different stack heights at jump target: 2 != 1]

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

Versions: vungleAdapter = "7.4.2.1"
newrelic = "7.6.1"

* ex: Browser name and version:
* ex: Operating System and version:

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by ndesai-newrelic** [comment]
@mmanuja To resolve the current issue, please add the following configuration to your app-level build.gradle file:

newrelic {
    // Exclude Amplitude classes from instrumentation
    excludePackageInstrumentation("com.vungle.*")
}
What This Does
This configuration tells NewRelic's SDK to exclude all classes in the com. vungle.* package from its instrumentation process.

We've already fixed this issue. We'll release the fix after Thanksgiving week.

**Comment by mmanuja** [comment]
@ndesai-newrelic I tried that however error is still there. I feel maybe I need to enter different package name 

I tried excluding these but still not working for me
    excludePackageInstrumentation("com.applovin.mediation.adapters.vungle")
    excludePackageInstrumentation("com.applovin.sdk")


I have these dependencies related to applovin which is using vungle 

applovin-sdk = { module = "com.applovin:applovin-sdk", version.ref = "applovinSdk" }
vungle-adapter = { module = "com.applovin.mediation:vungle-adapter", version.ref = "vungleAdapter" }
unityads-adapter = { module = "com.applovin.mediation:unityads-adapter", version.ref = "unityadsAdapter" }

**Comment by ndesai-newrelic** [comment]
@mmanuja can you share sample app?

**Comment by mmanuja** [comment]
@ndesai-newrelic Sure, I have created the sample project here https://github.com/mmanuja/sample_new_relic

**Comment by mohitmanuja** [comment]
@ndesai-newrelic Thanks for the update!

**Comment by ndesai-newrelic** [comment]
@mohitmanuja the issue is fixed in latest android agent release 7.6.2.
